sudo: false
dist: trusty
language: php
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
after_success: bash bin/deploy.sh
env:
  global:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_TRAVISCI=travis:phpunit
  - SVN_REPO: https://plugins.svn.wordpress.org/cosy-address-book/
  - GH_REF: https://github.com/1and1/wp-cosy-address-book.git
  - secure: "ToNKLu/6XQsjOoUHS5xAuk6TbjVNrWOLuDVvzNAdSG7jsFsgA0KPZgCk4PV8x/v+kD+LGEwUKuYk9h8eV2DvpiaYa/XEMbjtdeJxe/4QnFEFkMcKxF6FVDRp+fuiB7oXFgw+Bd3RXrtGhTHbVNphP7arBEOQEs33zXNK4qYCPlIRYErgCwJ1d0AONlI9bLO5peEH9Y2oqyjElyotd5NiK94Y0OIuYW9GH0EbqVtL/gsksoUU/PJzMYO2jZ7gH79sL/+L1S81gIq38RlkJD+Aq03EqMUmlPKgp7pgRO5h91yz8oJ7k1pp6kacJxGynk/9kQQqQTAU1Jl8y1qamMC4y0u9iLQUpmiiG2SWbD7gWWLxz4TbvInzGfiAqpBSxHHQlEIUyp618GiDaZgWHbUUond8zxUc3wo0cT88RM+eTx5OO8TQHcrYWJEabcQFfbx0u53xfbm0sd40iLJYhk6OFB7ikufP/i7kpNJj2BuQpEklMxlVHGDimDOkg/LYxqjhYA25bcAKlSHhQwrUl7O0rWPhuPR5U/l/2GlMjDBhpdi4UsyzMHNxU+MhrYkWzmnGlpo/2HDn737IfllqnqWGz9655YjpKHblwc3tutpY4ScfIc/3GEP60NgVPS5xmMLWn5z5wt2wnB/kU8CMTNDAP/nFcWq89tR2yT6hYf5bQ5M="
matrix:
  include:
  - php: 7.3
  - php: 7.2
  - php: 7.1
  - php: 7.0
  - php: 5.6
    env: WP_PLUGIN_DEPLOY=1
before_script:
- |
  # Remove Xdebug for a huge performance increase:
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  # Export Composer's global bin dir to PATH:
  composer config --list --global
  export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
- |
  # Install the specified version of PHPUnit depending on the PHP version:
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
    case "$TRAVIS_PHP_VERSION" in
      7.3|7.2|7.1|7.0|nightly)
        echo "Using PHPUnit 6.x"
        composer global require "phpunit/phpunit:^6"
        ;;
      5.6)
        echo "Using PHPUnit 5.x"
        composer global require "phpunit/phpunit:^5"
        ;;
      *)
        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
        exit 1
        ;;
    esac
  fi
  if [[ "$WP_TRAVISCI" == "travis:phpcs" ]] ; then
      composer install
  fi

- mysql --version
- phpenv versions
- php --version
- php -m
- which phpunit
- phpunit --version
- curl --version
- grunt --version
- git --version
- svn --version
- locale -a
before_install:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
    if [[ ! -z "$WP_VERSION" ]] ; then
      set -e
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      set +e
    fi
script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      # Run the build because otherwise there will be a bunch of warnings about
      # failed `stat` calls from `filemtime()`.
      echo Running with the following versions:
      php -v
      phpunit --version
      # Run PHPUnit tests
      phpunit || exit 1
      WP_MULTISITE=1 phpunit || exit 1
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpcs" ]] ; then
      ./vendor/bin/phpcs -p -s -v -n --standard=./phpcs.xml --extensions=php
    fi

