<?php
/**
 * Plugin Name:  1&1 IONOS Address Book
 * Plugin URI:   https://wordpress.org/plugins/cosy-address-book
 * Description:  Sends visitor contact data generated by contact forms embedded in WordPress websites to 1&1 IONOS Address Book
 * Version:      1.0.0
 * License:      MIT
 * Author:       1&1 IONOS
 * Author URI:   https://www.ionos.com
 * Text Domain:  cosy-address-book
 * Domain Path:  /languages
 */
/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Online: http://www.gnu.org/licenses/gpl.txt
 */
require_once WPMU_PLUGIN_DIR . '/cosy-address-book/cosy-address-book.php';