<?php
/**
 * Plugin Name:  IONOS Address Book
 * Plugin URI:   https://wordpress.org/plugins/cosy-address-book
 * Description:  Sends visitor contact data generated by contact forms embedded in WordPress websites to 1&1 IONOS Address Book
 * Version:      2.0.0
 * License:      MIT
 * Author:       IONOS
 * Author URI:   https://www.ionos.com
 * Text Domain:  cosy-address-book
 * Domain Path:  /languages
 */
require_once WPMU_PLUGIN_DIR . '/cosy-address-book/cosy-address-book.php';